blueprint:
  name: ROBB ROB_200-008-0-V2 Z2M V2
  description: "This blueprint is for the 4-Button-Switch ROBB ROB_200-008-0 dimmer switch when used with zigbee2mqtt V2.
  It is for general use so all buttons can be connected to any action of your choice.
  Make sure to select the correct device for the remote."
  domain: automation
  input:
    remote:
      name: Remote
      description: Dimmer remote to use
      selector:
        device:
          multiple: false
    on_button_1_short:
      name: On button 1 - short
      default: []
      selector:
        action: {}
    off_button_1_short:
      name: Off button 1 - short
      default: []
      selector:
        action: {}
    on_button_1_hold:
      name: On button 1 - hold
      default: []
      selector:
        action: {}
    off_button_1_hold:
      name: Off button 1 - hold
      default: []
      selector:
        action: {}
    button_1_release:
      name: Button 1 - release
      default: []
      selector:
        action: {}
    on_button_2_short:
      name: On button 2 - short
      default: []
      selector:
        action: {}
    off_button_2_short:
      name: Off button 2 - short
      default: []
      selector:
        action: {}
    on_button_2_hold:
      name: On button 2 - hold
      default: []
      selector:
        action: {}
    off_button_2_hold:
      name: Off button 2 - hold
      default: []
      selector:
        action: {}
    button_2_release:
      name: Button 2 - release
      default: []
      selector:
        action: {}
     
triggers:
  - trigger: device
    domain: mqtt
    id: on_1
    device_id: !input "remote"
    type: action
    subtype: on_1
  - trigger: device
    domain: mqtt
    id: off_1
    device_id: !input "remote"
    type: action
    subtype: off_1
  - trigger: device
    domain: mqtt
    id: brightness_move_up_1
    device_id: !input "remote"
    type: action
    subtype: brightness_move_up_1
  - trigger: device
    domain: mqtt
    id: brightness_move_down_1
    device_id: !input "remote"
    type: action
    subtype: brightness_move_down_1
  - trigger: device
    domain: mqtt
    id: brightness_stop_1
    device_id: !input "remote"
    type: action
    subtype: brightness_stop_1

  - trigger: device
    domain: mqtt
    id: on_2
    device_id: !input "remote"
    type: action
    subtype: on_2
  - trigger: device
    domain: mqtt
    id: off_2
    device_id: !input "remote"
    type: action
    subtype: off_2
  - trigger: device
    domain: mqtt
    id: brightness_move_up_2
    device_id: !input "remote"
    type: action
    subtype: brightness_move_up_2
  - trigger: device
    domain: mqtt
    id: brightness_move_down_2
    device_id: !input "remote"
    type: action
    subtype: brightness_move_down_2
  - trigger: device
    domain: mqtt
    id: brightness_stop_2
    device_id: !input "remote"
    type: action
    subtype: brightness_stop_2

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_1
        sequence: !input "on_button_1_short"
      - conditions:
          - condition: trigger
            id: off_1
        sequence: !input "off_button_1_short"
      - conditions:
          - condition: trigger
            id: brightness_move_up_1
        sequence: !input "on_button_1_hold"
      - conditions:
          - condition: trigger
            id: brightness_move_down_1
        sequence: !input "off_button_1_hold"
      - conditions:
          - condition: trigger
            id: brightness_stop_1
        sequence: !input "button_1_release"

      - conditions:
          - condition: trigger
            id: on_2
        sequence: !input "on_button_2_short"
      - conditions:
          - condition: trigger
            id: off_2
        sequence: !input "off_button_2_short"
      - conditions:
          - condition: trigger
            id: brightness_move_up_2
        sequence: !input "on_button_2_hold"
      - conditions:
          - condition: trigger
            id: brightness_move_down_2
        sequence: !input "off_button_2_hold"
      - conditions:
          - condition: trigger
            id: brightness_stop_2
        sequence: !input "button_2_release"


mode: single
